name: Build Windows VS2022

on:
  workflow_dispatch:  # 手动触发

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Check out source code
      uses: actions/checkout@v4

    # 安装 Rust（Windows 环境）
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    # 编译
    - name: Compile with VS2022
      run: |
        git submodule update --init --recursive
        cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -G "Visual Studio 17 2022"
        cmake --build build --config Release -j
        cmake --install build --prefix dist        

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-dist
        path: dist